databucket:
  title: Databucket

jwt:
  secret: veryverysecret
#  expire.hours: 24

server:
  port: 8080
  servlet.context-path: /

spring:
  jpa:
    hibernate.ddl-auto: update
    open-in-view: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false