spring:
  jpa:
    hibernate.ddl-auto: update
    open-in-view: true
    properties:
      hibernate.session_factory.interceptor: pl.databucket.tenant.EntityInterceptor

logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate: error
    pl.databucket.service.data.DataService: error